### ISSUE TITLE
Scope and milestones

### ISSUE THREAD

**Issue by plowzzer** [plowzzer/video-maker#1]
- [ ] **Main**
  - [x] Ask for search term
  - [x] Ask for prefix
  - [x] Start text bot
  - [x] Start image bot
  - [x] Start video bot
  - [ ] Start Youtube bot

---

- [x] **Text Bot**
  - [x] Data structure
  - [x] Get content from Wikipedia
  - [x] Clean unnecessary content  
  - [x] Breaking sentences
  - [x] IBM Watson interpretation
  - [x] Add tags
  - [x] Save data structure

---

- [x] **Image Bot**
  - [x] Load data structure
  - [x] Search image on Google Images
  - [x] Download Images
  - [x] Save data structure

---

- [x]  **Video Bot**
  - [x] Prepare and render images
  - [x] Create sentences with images
  - [x] Create Thumbnail for Youtube
  - [x] Renderer with After Effects

---

- [ ] **Youtube Bot**
  - [ ] Auth with OAuth
  - [ ] Upload video
  - [ ] Upload Thumbnail
